name: swe_632_lottery
description: A lottery web app built for the GMU SWE 632 class.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for the web app.
version: 0.5.1+19

environment:
  sdk: ">=3.0.6 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  scratcher: ^2.4.0
  flutter_fortune_wheel: ^1.3.0
  shimmer: ^3.0.0
  flutter_card_swiper: ^6.0.0
  confetti: ^0.7.0
  auto_animated: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included.
  uses-material-design: true

  # The following defines the path to the assets.
  assets:
    - assets/images/decor/
    - assets/images/items/
    - assets/images/coins/
